
- name: Update homebrew and upgrade all packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install homebrew packages list from config file
  homebrew:
    name: "{{applications}}"
    state: latest
