download_home: ~

applications:
  # - ansible # Installed via Pip during install
  - openjdk
  - wget
  - node
  - openssl
  - tmux
  - pyenv
  - java
  - curl
  - gradle
  - node
  - npm
  - openssl
  - maven
  - wget
  - terraform
  - awscli@1
  - kubernetes-cli

homebrew_cask_appdir: /Applications
cask_applications:
   - atom
   - docker
   - slack
   - sketch
   - vagrant
   - iterm2
   - postman
   - virtualbox
   - virtualbox-extension-pack
   - visual-studio-code
   - google-chrome
   - handbrake
   - sublime-text

#Mac store apps
mas_email: "{{ lookup('env','mas_email') }}"
mas_password: "{{ lookup('env','mas_password') }}"

mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
  - { id: 1278508951, name: "Trello" }
  - { id: 406056744, name: "Evernote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }


downloads:
   spotify:
     name: Spotify
     url: http://https://www.spotify.com/uk/download/mac/
     dest: "{{download_home}}/Downloads/Spotify.zip"
   ipvanish:
     name: IPVanish
     url: https://www.ipvanish.com/software/osx/IPVanish.dmg
     dest: "{{download_home}}/Downloads/IPVanish.dmg"

     