download_home: ~

applications:
  # - ansible # Installed via Pip during install
  - openjdk
  - wget
  - node
  - openssl
  - tmux
  - pyenv
  - java
  - curl
  - gradle
  - node
  - npm
  - openssl
  - maven
  - wget
  - terraform
  - awscli@1
  - kubernetes-cli

homebrew_cask_appdir: /Applications
cask_applications:
   - atom
   - docker
   - slack
   - sketch
   - vagrant
   - iterm2
   - postman
   - virtualbox
   - virtualbox-extension-pack
   - visual-studio-code
   - google-chrome
   - handbrake
   - sublime-text

#Mac store apps
mas_email: 
  secure: "EV+C9I/lUzhQzS2DWcDejzVPm3lyUGTqnpy2u6n+Ce6eqWN7WOY5b7AieDMAqwWZl8fTJiJy/gatC0aHNY15HgvYxsOtK0lnBOiV3Lp75hXqVl9+5tM2FDy1q2qOWJBsNqUAS+SXJwlkGLgwI3057qBbAACHisgWTVgZ2jUeB1dllAQArqXze4eqQ1CiYy4Qbf/PxsoVa3g7PnVNCNN50D652LoKZmwG97Ggn26ONp/JxxvlkCRt+xq8ILcZbE9O/cytIT6oSTXs5lG52axVlFXnARH50B1pZ9wObtjjeFLTxC2lZKfT3FHMdWKSbB2swmiNIJGQVhKkKBnzg72SiCFYp+zU4rwKdUofDqHFopfSxM5sDPIEtH7Cvv1cquMCqmChuNUQNQ91rlRPA+NW3bBWzQTGkWkjUoL0OIFKvnjopb04bEdeNH171MW1DWvCiMPdKsHrXwuJMLtwugi3XBqC2pOm8DMUnWfmtcfqmEPtt9BgQxKqFvgqah/zdEOyvx347TCc1dXz73QaT1JiFvrMk/CL31S4/fgkzCKaVLEsalkUn8Hzae4r+1nAk+9Tyq2viSkfap+nxLLp/983OUx9vY0DaC8eaF6QaRaMrNKUO3w2VbOag4qSsMJa0syvIlo6ufo38LPDeN57hAAH5Qry8vVHtaE/GwS/GjXDxnc="
mas_password: 
  secure: "a+q0CTcAe5RRLd2x3Gf2QMcSagOeMQWAt5VNX3erThHlzMObb8NrFjgPwgBbQ0nmAvcCy78wmn9q7dnzegPghV5vjggVTV5GA45WqWt5HN79js10d4ODALPc4gGPPuuq/EbLtNXW1Mulyms+mJWEoxGFfkpKW+nytHdnn0NjoJRyJ3gl3iK8mp861HxN8tcAh3exRiLLI0pdqFpMY2/BJ0vAJ96EkMCjQtjIecIZhWb+na70FIdz7jMAqK/2WK6VqEiUyb/vsRDqa6OGyEz6IMbUXBxROomw8+MWfkwM2WKlKIXyGfq9WzGbIda3Pv7vEqP3giduBdirufQi58XvaKESRJZAMM6BWRuYEx0XQV37Iu9Zk7q5+eK+CGKuOiiW03G0Z7iN5Ol7mY22wccwv0zah/rwQjL9O/fD/gq6tBU9OZk9eCXaKWSFleEcXFY0vQwJxDX4M4Cu94FSbnG/FLZze9YHAmMP7cmokLEiySm2hsWCl/Zy96tECP7KrFpZCPJ5zaaoN6jb+kUoI7jPiP4sD/kIq3buvwJhrgKc+FAimU3DTH+rUb14JxL3xgH8kjoeBUbgaBLHae0Sj2Puky/BEGmIBWlrMRCtXcyS9TL7dARRkeiLrA8rjrlYhUQWiiyNVUvL8h2s4L+Vw9o+oJ/f/217Xuu4wcOJZNgeQLk="

mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
  - { id: 1278508951, name: "Trello" }
  - { id: 406056744, name: "Evernote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }


downloads:
   spotify:
     name: Spotify
     url: http://https://www.spotify.com/uk/download/mac/
     dest: "{{download_home}}/Downloads/Spotify.zip"
   ipvanish:
     name: IPVanish
     url: https://www.ipvanish.com/software/osx/IPVanish.dmg
     dest: "{{download_home}}/Downloads/IPVanish.dmg"

     