download_home: "~"

homebrew_upgrade_all_packages: yes

homebrew_installed_packages:
  # - ansible # Installed via Pip during install
  - openjdk
  - wget
  - node
  - openssl
  - tmux
  - pyenv
  - java
  - curl
  - gradle
  - node
  - npm
  - openssl
  - maven
  - wget
  - terraform
  - awscli@1
  - kubernetes-cli

homebrew_cask_apps:
   - atom
   - docker
   - slack
   - sketch
   - vagrant
   - iterm2
   - postman
   - virtualbox
   - virtualbox-extension-pack
   - visual-studio-code
   - google-chrome
   - handbrake
   - sublime-text

#Mac store apps
mas_email: "{{ lookup('env','MAS_EMAIL') }}"
mas_password: "{{ lookup('env','MAS_PASSWORD') }}"

mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
  - { id: 1278508951, name: "Trello" }
  - { id: 406056744, name: "Evernote" }
  - { id: 404705039, name: "idraw" }
  - { id: 409201541, name: "Pages" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }

downloads:
   spotify:
     name: Spotify
     url: http://download.spotify.com/Spotify.dmg
     dest: "{{ download_home }}/Downloads/Spotify.dmg"
   ipvanish:
     name: IPVanish
     url: https://www.ipvanish.com/software/osx/IPVanish.dmg
     dest: "{{ download_home }}/Downloads/IPVanish.dmg"
   keepassx:
     name: KeePassX
     url: https://www.keepassx.org/releases/2.0.3/KeePassX-2.0.3.dmg
     dest: "{{ download_home }}/Downloads/KeePassX-2.0.3.dmg"
   androidstudio:
     name: AndroidStudio
     url: https://dl.google.com/dl/android/studio/install/3.6.1.0/android-studio-ide-192.6241897-mac.dmg
     dest: "{{ download_home }}/Downloads/android-studio-ide.dmg"