#!/usr/bin/env ansible-playbook
- hosts: macbook
  connection: local
  tasks:
  - debug:
      msg: Check we are running in the directory of the script
    failed_when: not ansible_env.PWD.endswith('/mac-ansible')

- hosts: macbook
  connection: local
  roles:
  - test
