#!/usr/bin/env ansible-playbook
- hosts: macbook
  connection: local
  pre_tasks:
  - name: Load user-provided configuration_variables
    include_vars: "config-options.yml"
    no_log: true
    check_mode: no
    tags:
      - always
  tasks:
  - debug:
      msg: "Start Provisioning"
  - import_role:
      name: common
  - import_role:
      name: geerlingguy.mas
  - import_role:
      name: developer
  - debug:
      msg: "Completed Provisioning"
